# Generated by Django 2.2.2 on 2019-06-30 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveIntegerField(verbose_name='start point coordiate X')),
                ('start_y', models.PositiveIntegerField(verbose_name='start point coordinate Y')),
                ('end_x', models.PositiveIntegerField(verbose_name='end point coordiate X')),
                ('end_y', models.PositiveIntegerField(verbose_name='end point coordinate Y')),
                ('instructions', django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='List of instructions. For example: [["START", [1, 2]], ["GO", ["E", 5]], ["TURN", "R"], ["REACH", "The Bridge"], ["GO", [null, 8]]]', verbose_name='instructions')),
            ],
            options={
                'unique_together': {('start_x', 'start_y'), ('end_x', 'end_y')},
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(verbose_name='coordinate X')),
                ('y', models.PositiveIntegerField(verbose_name='coordinate Y')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
            ],
            options={
                'unique_together': {('x', 'y')},
            },
        ),
    ]
